"""add_produtos

Revision ID: 0a39550b76d6
Revises: d472a426a4a1
Create Date: 2026-04-26 22:32:19.191762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a39550b76d6'
down_revision: Union[str, None] = 'd472a426a4a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('preco_custo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preco_venda', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estoque_atual', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('estoque_minimo', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_table('produtos')
    # ### end Alembic commands ###
