"""add credito_utilizado to pagamentos

Revision ID: 0b30d888200d
Revises: 76145725565d
Create Date: 2026-05-28 15:06:07.866378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b30d888200d'
down_revision: Union[str, None] = '76145725565d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('saldo_credito', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('pagamentos', sa.Column('credito_utilizado', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagamentos', 'credito_utilizado')
    op.drop_column('clientes', 'saldo_credito')
    # ### end Alembic commands ###
