"""Add id_legado to Agendamento

Revision ID: 76145725565d
Revises: i4j5k6l7m8n9
Create Date: 2026-05-28 14:24:37.844843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76145725565d'
down_revision: Union[str, None] = 'i4j5k6l7m8n9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendamentos', sa.Column('id_legado', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_agendamentos_id_legado'), 'agendamentos', ['id_legado'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agendamentos_id_legado'), table_name='agendamentos')
    op.drop_column('agendamentos', 'id_legado')
    # ### end Alembic commands ###
