"""produto_sem_unidade_estoque_int

Revision ID: 861175356c9f
Revises: 0a39550b76d6
Create Date: 2026-04-26 22:39:13.579509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '861175356c9f'
down_revision: Union[str, None] = '0a39550b76d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('produtos', 'estoque_atual',
               existing_type=mysql.DECIMAL(precision=10, scale=3),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('produtos', 'estoque_minimo',
               existing_type=mysql.DECIMAL(precision=10, scale=3),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_column('produtos', 'unidade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('unidade', mysql.VARCHAR(length=20), nullable=False))
    op.alter_column('produtos', 'estoque_minimo',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=10, scale=3),
               existing_nullable=False)
    op.alter_column('produtos', 'estoque_atual',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=10, scale=3),
               existing_nullable=False)
    # ### end Alembic commands ###
