"""initial_schema

Revision ID: 90255258a610
Revises: 
Create Date: 2026-04-24 15:31:13.893451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90255258a610'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agendamentos_id'), 'agendamentos', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_google_tokens_id'), 'google_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_itens_agendamento_data_hora_inicio'), 'itens_agendamento', ['data_hora_inicio'], unique=False)
    op.create_index(op.f('ix_itens_agendamento_id'), 'itens_agendamento', ['id'], unique=False)
    op.drop_constraint('itens_agendamento_ibfk_1', 'itens_agendamento', type_='foreignkey')
    op.create_foreign_key(None, 'itens_agendamento', 'agendamentos', ['agendamento_id'], ['id'])
    op.create_index(op.f('ix_pagamentos_id'), 'pagamentos', ['id'], unique=False)
    op.create_index(op.f('ix_profissionais_id'), 'profissionais', ['id'], unique=False)
    op.create_index(op.f('ix_servicos_id'), 'servicos', ['id'], unique=False)
    op.drop_index('email', table_name='usuarios')
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.create_index('email', 'usuarios', ['email'], unique=True)
    op.drop_index(op.f('ix_servicos_id'), table_name='servicos')
    op.drop_index(op.f('ix_profissionais_id'), table_name='profissionais')
    op.drop_index(op.f('ix_pagamentos_id'), table_name='pagamentos')
    op.drop_constraint(None, 'itens_agendamento', type_='foreignkey')
    op.create_foreign_key('itens_agendamento_ibfk_1', 'itens_agendamento', 'agendamentos', ['agendamento_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_itens_agendamento_id'), table_name='itens_agendamento')
    op.drop_index(op.f('ix_itens_agendamento_data_hora_inicio'), table_name='itens_agendamento')
    op.drop_index(op.f('ix_google_tokens_id'), table_name='google_tokens')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_index(op.f('ix_agendamentos_id'), table_name='agendamentos')
    # ### end Alembic commands ###
